jobs:

# jobs for the Nouvola sample application

################################

# add pipeline job
# Run API tests on Nouvola cloud
  - name: test-api-nouvola-run-tests
    type: runSh
    steps:
      - IN: test-api-nouvola-api-params
      - IN: dr-github
        switch: off
      - TASK:
        - script: ls -R $DRGITHUB_PATH
        - script: echo $$DRGITHUB_PATH 
        - script: . $DRGITHUB_PATH/gitRepo/run-nouvola-test.sh
    flags:
      - test-api-nouvola
