jobs:

# jobs for the Nouvola sample application

################################

# add pipeline job
# Run API tests on Nouvola cloud
  - name: test-api-nouvola-run-tests
    type: runSh
    steps:
      - IN: test-api-nouvola-api-params
      - IN: github-repo
        switch: off
      - TASK:
        - script: echo "API KEY "$NOUVOLA_API_KEY
        - script: echo "PLAN ID "$NOUVOLA_PLAN_ID
        - script: echo $NOUVOLA_PLAN_ID
        - script: ls -l . $GITHUBREPO_PATH/gitRepo/run-nouvola-tests.sh
        - script: . $GITHUBREPO_PATH/gitRepo/run-nouvola-tests.sh
    flags:
      - test-api-nouvola
