jobs:

# jobs for the Nouvola sample application

################################

# add pipeline job
# Run API tests on Nouvola cloud
  - name: test-api-nouvola-run-tests
    type: runSh
    steps:
      - IN: test-api-nouvola-api-params
      - TASK:
        - script: ls -R $SHIPPABLE_BUILD_DIR
        - script: ./IN/test-api-nouvola/gitRepo/run-nouvola-test.sh
    flags:
      - test-api-nouvola
